### ISSUE TITLE
Add support for generic types in corroborate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rowiki/wikiro#29]
```
We still need to retrieve the database fields from the config and introduce a 
way to skip already populated fields.

We also need to get rid of special cases (trated in Issue 18 and Issue 19)


```

Original issue reported on code.google.com by `strain...@gmail.com` on 15 Feb 2015 at 11:01
* Blocking: #17, #19, #18

**Comment by strainu** [comment]
Resolved some time in 2015, when we added support for RAN. More fixes where made in 2016, when we added WLE MD.
